import test from 'node:test';import assert from 'node:assert/strict';import {Readable} from 'node:stream';import {createHmac} from 'node:crypto';
import {passwordHash,checkPassword,totp,checkTotp,originCheck,hash,session,rate} from '../lib/security.mjs';import {registration} from '../lib/validation.mjs';import {signature,confirmPayment} from '../lib/payments.mjs';import handler from '../api/index.js';
process.env.DATABASE_URL='postgresql://test:test@ep-test.us-east-2.aws.neon.tech/test';process.env.APP_URL='https://tournament.example';process.env.RAZORPAY_KEY_ID='rzp_test_fixture';process.env.RAZORPAY_KEY_SECRET='test-secret';process.env.RAZORPAY_WEBHOOK_SECRET='webhook-secret';process.env.SESSION_SECRET='test-session-secret-only';
const originalFetch=global.fetch;let calls=[];
function mock(resolver){calls=[];global.fetch=async(url,options={})=>{const body=options.body?JSON.parse(options.body):null;const entry={url:String(url),body,options};calls.push(entry);const result=await resolver(entry);return new Response(JSON.stringify(result),{status:200,headers:{'Content-Type':'application/json'}});};}
const request=async(route,body={},headers={},method='POST')=>{const raw=typeof body==='string'?body:JSON.stringify(body);const req=Readable.from(method==='GET'?[]:[raw]);req.method=method;req.url='/api/'+route;req.headers={origin:'https://tournament.example',...headers};req.socket={remoteAddress:'127.0.0.1'};let status,output,storedHeaders={};const res={setHeader(k,v){storedHeaders[k]=v;},writeHead(s,h){status=s;Object.assign(storedHeaders,h);},end(value){output=value;}};await handler(req,res);return {status,headers:storedHeaders,data:(storedHeaders['Content-Type']||'').startsWith('application/json')?JSON.parse(output):output};};
const input={name:'Test Student',email:'student@example.com',phone:'9876543210',college:'Unlisted Indore College',year:'2nd year',chess_username:'test_student',consent:true};
const row={id:'11111111-1111-4111-8111-111111111111',reference:'TZ-2026-123456789ABC',amount:5000,order_id:'order_test',status:'pending',access_hash:hash('access-test')};
const goodPayment={id:'pay_test',order_id:'order_test',amount:5000,currency:'INR',status:'captured'};

test('password is salted, verifies correctly and rejects a wrong password',()=>{const digest=passwordHash('long-test-password');assert.ok(checkPassword('long-test-password',digest));assert.equal(checkPassword('incorrect',digest),false);assert.notEqual(passwordHash('long-test-password'),digest);});
test('TOTP matches the RFC 6238 six-digit reference vector',()=>{assert.equal(totp('GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ',59000),'287082');assert.equal(checkTotp('abcdef','GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ'),false);});
test('registration accepts a custom college and normalises email and phone',()=>{const r=registration({...input,email:'Student@Example.com',phone:'+91 9876543210'});assert.equal(r.email,'student@example.com');assert.equal(r.phone,'9876543210');assert.equal(r.college,input.college);});
test('registration rejects missing consent, bad phone, URL username and bad year',()=>{for(const edit of [{consent:false},{phone:'12345'},{chess_username:'https://chess.com/player'},{year:'Year 99'},{website:'spam'}])assert.throws(()=>registration({...input,...edit}));});
test('cross-origin requests are rejected',()=>{assert.throws(()=>originCheck({headers:{origin:'https://attacker.example'}}));assert.doesNotThrow(()=>originCheck({headers:{origin:'https://tournament.example'}}));});
test('admin data rejects anonymous requests before querying data',async()=>{mock(()=>{throw Error('Should not query DB');});const r=await request('admin/data',{}, {},'GET');assert.equal(r.status,401);assert.equal(calls.length,0);});
test('admin mutations reject a missing CSRF token',async()=>{mock(()=>({rows:[{csrf:'real-csrf',token_hash:'test',expires_at:new Date(Date.now()+100000).toISOString()}]}));await assert.rejects(()=>session({headers:{cookie:'tz_admin=test-session'}},true),e=>e.status===403);});
test('rate limit is persisted and rejects over-limit attempts',async()=>{mock(()=>({rows:[{count:6}]}));await assert.rejects(()=>rate({headers:{},socket:{remoteAddress:'127.0.0.1'}},'login',5),e=>e.status===429);assert.match(calls[0].body.query,/ON CONFLICT/);});
test('payment signature rejects a tampered order',()=>{const sig=createHmac('sha256','test-secret').update('order_test|pay_test').digest('hex');assert.equal(signature('order_test|pay_test',sig,'test-secret'),true);assert.equal(signature('order_wrong|pay_test',sig,'test-secret'),false);});
test('amount, currency, order and captured state must all match',async()=>{for(const changed of [{amount:100},{currency:'USD'},{order_id:'wrong'},{status:'authorized'}]){mock(e=>e.url.includes('razorpay')?{...goodPayment,...changed}:{rows:[]});await assert.rejects(()=>confirmPayment(row,'pay_test'));assert.equal(calls.filter(e=>e.url.endsWith('/sql')).length,0);}});
test('valid captured payment atomically confirms a pending registration',async()=>{mock(e=>e.url.includes('razorpay')?goodPayment:{rows:[]});await confirmPayment(row,'pay_test');assert.match(calls[1].body.query,/status='pending'/);assert.deepEqual(calls[1].body.params,['pay_test',row.id]);});
test('bad webhook signature is rejected before accessing the database',async()=>{mock(()=>{throw Error('Unexpected database call');});const r=await request('webhook',{event:'payment.captured'},{'x-razorpay-signature':'forged'});assert.equal(r.status,400);assert.equal(calls.length,0);});
test('valid signed captured webhook checks provider payment and confirms',async()=>{mock(e=>e.url.includes('razorpay')?goodPayment:{rows:e.body.query.startsWith('SELECT')?[row]:[]});const raw=JSON.stringify({event:'payment.captured',payload:{payment:{entity:goodPayment}}});const sig=createHmac('sha256','webhook-secret').update(raw).digest('hex');const r=await request('webhook',raw,{'x-razorpay-signature':sig});assert.equal(r.status,200);assert.equal(calls.length,3);});
test('client payment verification rejects a forged signature',async()=>{mock(e=>({rows:e.body.query.includes('rate_limits')?[{count:1}]:[row]}));const r=await request('verify',{reference:row.reference,access:'access-test',razorpay_order_id:'order_test',razorpay_payment_id:'pay_test',razorpay_signature:'forged'});assert.equal(r.status,400);assert.equal(calls.some(e=>e.url.includes('razorpay')),false);});
test('registration fee comes from database settings, never the request body',async()=>{mock(e=>({rows:e.body.query.includes('rate_limits')?[{count:1}]:e.body.query.includes('tournament_settings')?[{status:'open',fee_paise:5000}]:[]}));const r=await request('register',{...input,amount:1,fee_paise:1});assert.equal(r.status,201);const insert=calls.find(e=>e.body.query.startsWith('INSERT INTO registrations'));assert.equal(insert.body.params.at(-1),'5000');assert.equal(r.data.amount,5000);assert.match(r.data.reference,/^TZ-\d{4}-[A-F0-9]{12}$/);assert.equal(r.data.access.length,64);assert.equal(insert.body.params[2],hash(r.data.access));});
test('SQL-like input is passed as a parameter instead of executable SQL',async()=>{const name="Robert'); DROP TABLE registrations; --";mock(e=>({rows:e.body.query.includes('rate_limits')?[{count:1}]:e.body.query.includes('tournament_settings')?[{status:'open',fee_paise:5000}]:[]}));const r=await request('register',{...input,name});assert.equal(r.status,201);const insert=calls.find(e=>e.body.query.startsWith('INSERT INTO registrations'));assert.ok(!insert.body.query.includes(name));assert.equal(insert.body.params[3],name);});
test('closed registration does not create a payment or a registration',async()=>{mock(e=>({rows:e.body.query.includes('rate_limits')?[{count:1}]:[{status:'closed',fee_paise:5000}]}));const r=await request('register',input);assert.equal(r.status,409);assert.equal(calls.some(e=>e.body.query.startsWith('INSERT INTO registrations')),false);});
test('private registration lookup requires matching reference and hashed access code',async()=>{mock(e=>({rows:e.body.query.includes('rate_limits')?[{count:1}]:[]}));const r=await request('status',{reference:row.reference,access:'wrong'});assert.equal(r.status,404);const query=calls.find(e=>e.body.query.startsWith('SELECT'));assert.deepEqual(query.body.params,[row.reference,hash('wrong')]);});
test('refund webhook only applies a matching full amount and never confirms a pending entry',async()=>{mock(()=>({rows:[]}));const raw=JSON.stringify({event:'refund.processed',payload:{refund:{entity:{id:'rfnd_test',payment_id:'pay_test',amount:5000}}}});const sig=createHmac('sha256','webhook-secret').update(raw).digest('hex');const r=await request('webhook',raw,{'x-razorpay-signature':sig});assert.equal(r.status,200);assert.match(calls[0].body.query,/amount=\$3/);assert.match(calls[0].body.query,/status IN \('paid','refund_pending','refunded'\)/);});
test('admin login requires both configured password and authenticator',async()=>{delete process.env.ADMIN_PASSWORD_HASH;delete process.env.ADMIN_TOTP_SECRET;const r=await request('login',{password:'fake',code:'123456'});assert.equal(r.status,503);});
test('HTTP endpoint rejects cross-origin mutation and oversized request',async()=>{assert.equal((await request('register',input,{origin:'https://evil.example'})).status,403);assert.equal((await request('register',{name:'x'.repeat(17000)})).status,413);});
test('unknown API paths do not reveal internals',async()=>{const r=await request('no-such-endpoint');assert.equal(r.status,404);assert.equal(r.data.error,'Endpoint not found.');});
test.after(()=>{global.fetch=originalFetch;});

test('password alone cannot sign in without a valid authenticator code',async()=>{process.env.ADMIN_PASSWORD_HASH=passwordHash('secure-test-password');process.env.ADMIN_TOTP_SECRET='GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ';mock(()=>({rows:[{count:1}]}));const r=await request('login',{password:'secure-test-password',code:'invalid'});assert.equal(r.status,401);assert.equal(r.headers['Set-Cookie'],undefined);});
test('repeated authenticator code cannot mint another admin session',async()=>{mock(e=>({rows:e.body.query.includes('rate_limits')?[{count:1}]:[]}));const r=await request('login',{password:'secure-test-password',code:totp(process.env.ADMIN_TOTP_SECRET)});assert.equal(r.status,401);assert.match(r.data.error,/already used/);});
test('successful two-factor sign-in issues an HTTP-only strict session cookie',async()=>{mock(e=>({rows:e.body.query.includes('rate_limits')?[{count:1}]:e.body.query.includes('totp_used')?[{code_hash:'fixture'}]:[]}));const r=await request('login',{password:'secure-test-password',code:totp(process.env.ADMIN_TOTP_SECRET)});assert.equal(r.status,200);assert.match(r.headers['Set-Cookie'],/HttpOnly/);assert.match(r.headers['Set-Cookie'],/SameSite=Strict/);assert.equal(r.data.csrf,undefined);});
test('duplicate refund request is rejected before any provider call',async()=>{mock(e=>({rows:e.body.query.includes('admin_sessions')?[{csrf:'csrf-test',token_hash:'session'}]:e.body.query.startsWith('SELECT * FROM registrations')?[{...row,status:'refund_pending',payment_id:'pay_test'}]:[]}));const r=await request('admin/refund',{id:row.id,confirm:row.reference},{cookie:'tz_admin=test','x-csrf-token':'csrf-test'});assert.equal(r.status,409);assert.equal(calls.some(e=>e.url.includes('razorpay')),false);});
test('deleting a paid entry preserves financial records and requires exact confirmation',async()=>{mock(e=>({rows:e.body.query.includes('admin_sessions')?[{csrf:'csrf-test',token_hash:'session'}]:e.body.query.startsWith('SELECT * FROM registrations')?[{...row,status:'paid',payment_id:'pay_test'}]:[]}));const headers={cookie:'tz_admin=test','x-csrf-token':'csrf-test'};const bad=await request('admin/delete',{id:row.id,confirm:'wrong'},headers);assert.equal(bad.status,400);const good=await request('admin/delete',{id:row.id,confirm:row.reference},headers);assert.equal(good.status,200);assert.ok(calls.some(e=>e.body.query.includes('SET deleted_at=now()')));assert.ok(!calls.some(e=>e.body.query.startsWith('DELETE FROM registrations')));});
